sudo: required
services:
  - docker

before_install:
  - docker build -t quimerait/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run quimerait/react-test npm test -- --coverage

after_success:
  - docker build -t quimerait/docker-multi-client ./client
  - docker build -t quimerait/docker-multi-nginx ./nginx  
  - docker build -t quimerait/docker-multi-server ./server
  - docker build -t quimerait/docker-multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those image and push them to docker hub
  - docker push quimerait/docker-multi-client
  - docker push quimerait/docker-multi-nginx
  - docker push quimerait/docker-multi-server
  - docker push quimerait/docker-multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: docker-multi
  env: DockerMulti-env
  bucket_name: elasticbeanstalk-us-east-1-610169282455
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY